"""empty message

Revision ID: cec2b019ab1e
Revises: b52467b959fb
Create Date: 2023-09-18 17:32:19.499461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec2b019ab1e'
down_revision = 'b52467b959fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_start_date_time', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('event_end_date_time', sa.String(length=15), nullable=False))
        batch_op.alter_column('event_time',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=25),
               existing_nullable=False)
        batch_op.drop_column('event_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credentials')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.alter_column('event_time',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
        batch_op.drop_column('event_end_date_time')
        batch_op.drop_column('event_start_date_time')

    # ### end Alembic commands ###
